#!/bin/bash

# Create a new file from a template

function usage() {
    cat <<EOF

    Usage: `basename $0` <FILE>
EOF
}

if [ -z $1 ]; then
    usage
    exit 1
fi

filename=$1

if [ -f $filename ]; then
    echo "File $filename already exists..."
    exit 1
fi

dir=`dirname $filename`

if [ ! -d $dir ]; then
    echo "The directory '$dir' does not exist."
    echo "Do you want to create it? [Y/n] "

    read choice

    if [ "$choice" = "n" ]; then
        exit 1
    fi

    mkdir -p $dir
fi


type=`echo $filename | cut -d '.' -f2`

cp templates/$type.tpl "$filename"

sed -i "s/<YEAR>/`date +%Y`/" $filename
sed -i "s/<AUTHOR>/`git config --global user.name`/" $filename
sed -i "s|<NAME>|$filename|" $filename
