#!/bin/bash

# Create a new file from a template

function usage() {
    cat <<EOF

    Usage: `basename $0` <FILE>
EOF
}

function error() {
    printf "\033[;31m" # red
    printf "\n$1\n"
    printf "\033[0m"   # no color
}

if [ -z $1 ]; then
    usage
    exit 1
fi

filename=$1

if [ -f $filename ]; then
    error "File $filename already exists!"
    exit 1
fi

# get absolute path of script directory
path=$(cd `dirname $0` && pwd)

type=`echo $filename | cut -d '.' -f 2`

if [ ! -f "$path/templates/$type.tpl" ]; then
    error "No template found for filetype '$type'"
    exit 1
fi


dir=`dirname $filename`

if [ ! -d $dir ]; then
    echo "The directory '$dir' does not exist."
    echo "Do you want to create it? [Y/n] "

    read choice

    if [ "$choice" = "n" ]; then
        exit 1
    fi

    mkdir -p $dir
fi


author=`git config user.name`

if [ -z "$author" ]; then
    author=`whoami`

    printf "\nNo git username found...\n"
    printf "Enter your name [$author]: "

    read choice

    if [ ! -z "$choice" ]; then
        author=$choice
    fi
fi


cp "$path"/templates/$type.tpl "$filename"

sed -i "/<LICENSE>/r $path/templates/LICENSE.tpl" $filename
sed -i "s/<LICENSE>//" $filename

sed -i "s/<YEAR>/`date +%Y`/" $filename
sed -i "s/<AUTHOR>/$author/" $filename
sed -i "s|<NAME>|$filename|" $filename

